--
-- PostgreSQL database dump
--

\restrict 3pVwQvf9GFfHQCnJzpo6P4Y7zW0oJrHK8ZEXxdz6XZgUT2hlrpdsA8G0hOg3ebV

-- Dumped from database version 16.8
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: components; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.components VALUES (3, '8a83ac2c-df44-44be-87b5-4a1e0c9abada', 'Separator', 'A visual separator with optional line and numbered indicator', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "color": {"enum": ["gray", "red", "green", "blue", "yellow"], "type": "string", "default": "gray", "description": "Color theme of the separator"}, "height": {"type": "number", "default": 40, "description": "Height of the separator in pixels"}, "number": {"type": "number", "default": 1, "description": "Number to display when showNumber is true"}, "showLine": {"type": "boolean", "default": true, "description": "Show the separator line"}, "showNumber": {"type": "boolean", "default": false, "description": "Show a numbered indicator"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'SeparatorBlock', 'static', 'content', NULL);
INSERT INTO public.components VALUES (10, '1ea4e8f8-2714-43f8-88dc-740f5d0b7f25', 'Scenario', 'An interactive scenario-based question with image background and multiple choice answers', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "image": {"type": "string", "required": true, "description": "Background image URL"}, "answers": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "text": {"type": "string"}, "order": {"type": "number"}, "isCorrect": {"type": "boolean"}}}, "required": true, "description": "Array of answer options"}, "question": {"type": "string", "required": true, "description": "The scenario question"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ScenarioBlock', 'static', 'content', NULL);
INSERT INTO public.components VALUES (11, '3fad323a-d678-4bfc-858c-c0312f522596', 'Graph', 'Display data as line, bar, pie, or donut charts using Recharts', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "data": {"type": "array", "items": {"type": "object", "properties": {"name": {"type": "string"}, "value": {"type": "number"}}}, "required": true, "description": "Array of data points"}, "title": {"type": "string", "description": "Chart title"}, "colors": {"type": "array", "items": {"type": "string"}, "description": "Array of colors for chart segments"}, "graphType": {"enum": ["line", "bar", "pie", "donut"], "type": "string", "required": true, "description": "Type of chart to display"}, "textStyle": {"type": "object", "description": "Text styling options"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'GraphBlock', 'static', 'content', NULL);
INSERT INTO public.components VALUES (7, '2a9a0a70-b10b-4f74-b35e-06963dedf376', 'Checkbox List', 'An interactive checklist with multiple style variants', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "text": {"type": "string"}, "checked": {"type": "boolean"}}}, "required": true, "description": "Array of checkbox items"}, "textStyle": {"type": "object", "description": "Text styling options"}, "blockStyle": {"enum": ["A", "B", "C"], "type": "string", "default": "A", "description": "Visual style variant"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'CheckboxBlock', 'interactive', 'content', NULL);
INSERT INTO public.components VALUES (8, 'd2dc5347-db07-4413-a0ad-8559b907d4ac', 'Tabs', 'A tabbed content container with optional images per tab', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "image": {"type": "string"}, "title": {"type": "string"}, "content": {"type": "string"}}}, "required": true, "description": "Array of tab items"}, "textStyle": {"type": "object", "description": "Text styling options"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'TabsBlock', 'interactive', 'content', NULL);
INSERT INTO public.components VALUES (20, '723123f1-7057-45ad-93dd-ac1c56cf6683', 'Labeled Image', 'An interactive image with positioned hotspots that reveal information popups', '{"alt": {"type": "string", "default": "Labeled image", "description": "Alt text for the image"}, "dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "image": {"type": "string", "required": true, "description": "Image URL"}, "items": {"type": "array", "items": {"type": "object", "properties": {"x": {"type": "number", "description": "X position as percentage (0-100)"}, "y": {"type": "number", "description": "Y position as percentage (0-100)"}, "id": {"type": "string"}, "title": {"type": "string"}, "content": {"type": "string"}}}, "required": true, "description": "Array of labeled hotspots"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'LabeledImageBlock', 'static', 'content', NULL);
INSERT INTO public.components VALUES (19, 'a4cf5e83-b089-4d81-a9f1-59c6e45c501f', 'Accordion', 'An expandable/collapsible accordion with optional images and multiple style variants', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "image": {"type": "string"}, "title": {"type": "string"}, "content": {"type": "string"}, "imagePosition": {"enum": ["left", "right", "top", "bottom", "stretched"], "type": "string"}}}, "required": true, "description": "Array of accordion items"}, "textStyle": {"type": "object", "description": "Text styling options"}, "blockStyle": {"enum": ["A", "B", "C"], "type": "string", "default": "A", "description": "Visual style variant"}, "allowMultiple": {"type": "boolean", "default": false, "description": "Allow multiple items to be open simultaneously"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'AccordionBlock', 'interactive', 'content', NULL);
INSERT INTO public.components VALUES (28, 'e30debb7-60a4-4b3d-92bd-d9f9370d95a8', 'Columns', 'A multi-column text layout block', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "columns": {"enum": [1, 2, 3, 4], "type": "number", "default": 2, "description": "Number of columns"}, "content": {"type": "string", "required": true, "description": "The text content"}, "contentStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ColumnsBlock', 'static', 'content', NULL);
INSERT INTO public.components VALUES (23, 'e61dcdc7-8241-494a-8177-08489433915a', 'Multiple Response', 'A multiple-answer question where users can select multiple correct options', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "text": {"type": "string"}, "isCorrect": {"type": "boolean"}}}, "required": true, "description": "Array of answer options"}, "question": {"type": "string", "description": "The question text"}, "textStyle": {"type": "object", "description": "Text styling options"}, "correctFeedback": {"type": "string", "description": "Feedback shown when all answers are correct"}, "incorrectFeedback": {"type": "string", "description": "Feedback shown when some answers are incorrect"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'MultipleResponseBlock', 'interactive', 'exercise', NULL);
INSERT INTO public.components VALUES (24, '31fbc773-e0c2-42c1-bf87-216e6aedc667', 'Fill in the Blank', 'A text completion exercise with blanks that users fill in', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "text": {"type": "string", "description": "Text with ___ placeholder for blank"}, "answers": {"type": "array", "items": {"type": "string"}, "description": "Array of acceptable correct answers"}}}, "required": true, "description": "Array of fill-in-the-blank items"}, "textStyle": {"type": "object", "description": "Text styling options"}, "placeholder": {"type": "string", "default": "___", "description": "Placeholder text for blanks"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'FillInTheBlankBlock', 'interactive', 'exercise', NULL);
INSERT INTO public.components VALUES (54, 'f99e0e25-8f0d-43b2-b7d0-9316d1d0d741', 'List', 'A versatile list component with multiple styles (bullets, checkmarks, numbered, cards, etc.)', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "string"}, "required": true, "description": "Array of list items"}, "ordered": {"type": "boolean", "default": false, "description": "Use ordered list (ol) instead of unordered (ul)"}, "listStyle": {"enum": ["default", "check", "circle", "arrow", "chevron", "star", "numbered", "gradient", "bordered", "cards"], "type": "string", "default": "default", "description": "Visual style of the list"}, "textStyle": {"type": "object", "description": "Text styling options"}, "accentColor": {"type": "string", "default": "#9F80DA", "description": "Accent color for icons and decorations"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ListBlock', 'static', 'content', NULL);
INSERT INTO public.components VALUES (64, 'daa193fa-cc71-4b54-b872-6439459e14f0', 'Story Telling', 'A character avatar with speech/thought bubble for narrative content', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "text": {"type": "string", "required": true, "description": "Speech/thought bubble text (max 1000 chars)"}, "textStyle": {"type": "object", "description": "Text styling options"}, "avatarName": {"type": "string", "description": "Character name displayed below avatar"}, "avatarImage": {"type": "string", "required": true, "description": "Avatar image URL"}, "bubbleStyle": {"type": "object", "properties": {"shape": {"enum": ["classic", "rounded", "cloud", "square", "thought"], "type": "string"}, "borderColor": {"type": "string"}, "borderWidth": {"type": "string"}, "backgroundColor": {"type": "string"}}, "description": "Bubble styling options"}, "avatarPosition": {"enum": ["left", "right"], "type": "string", "default": "left", "description": "Position of the avatar"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'StoryTellingBlock', 'static', 'content', NULL);
INSERT INTO public.components VALUES (55, '16565071-11d2-4bf5-8ce6-ad6f12478df9', 'Reviews', 'Display user reviews with ratings, names and avatars', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "reviews": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "name": {"type": "string"}, "avatar": {"type": "string"}, "rating": {"type": "number", "maximum": 5, "minimum": 1}, "review": {"type": "string"}}}, "required": true, "description": "Array of reviews"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ReviewsBlock', 'static', 'content', NULL);
INSERT INTO public.components VALUES (57, '259b078b-59ec-4663-b2f8-9b0ceea674f3', 'Audio', 'A custom audio player with play/pause, seek and volume controls', '{"url": {"type": "string", "required": true, "description": "Audio file URL"}, "dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "title": {"type": "string", "default": "Audio", "description": "Audio title"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'AudioBlock', 'interactive', 'content', NULL);
INSERT INTO public.components VALUES (59, '01cda612-07ce-43c7-a23f-d02074372c74', 'Embed', 'Embed external content via iframe or HTML with fullscreen support', '{"url": {"type": "string", "description": "URL to embed in iframe"}, "dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "html": {"type": "string", "description": "Raw HTML to embed"}, "title": {"type": "string", "default": "Embedded content", "description": "Title for accessibility"}, "maxHeight": {"type": "number", "description": "Maximum height in pixels (when aspectRatio is auto)"}, "aspectRatio": {"enum": ["16:9", "4:3", "1:1", "9:16", "auto"], "type": "string", "default": "16:9", "description": "Aspect ratio of the embed"}, "allowFullscreen": {"type": "boolean", "default": true, "description": "Allow fullscreen mode"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'EmbedBlock', 'interactive', 'content', NULL);
INSERT INTO public.components VALUES (61, '83a8b1cf-f9f8-472c-8f86-9ad367e83e12', 'Matching Pairs', 'An interactive matching exercise connecting items from two columns', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "itemsA": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "text": {"type": "string"}, "matchingNumber": {"type": "number"}}}, "required": true, "description": "Items for column A"}, "itemsB": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "text": {"type": "string"}, "matchingNumber": {"type": "number"}}}, "required": true, "description": "Items for column B (matched by matchingNumber)"}, "textStyle": {"type": "object", "description": "Text styling options"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'MatchingPairsBlock', 'interactive', 'exercise', NULL);
INSERT INTO public.components VALUES (63, '1ebfc5b8-cec5-4b74-99a6-fea0e9283f8a', 'Flash Cards', 'Interactive flip cards with question on front and answer on back', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "answer": {"type": "string"}, "question": {"type": "string"}}}, "required": true, "description": "Array of flash cards"}, "textStyle": {"type": "object", "description": "Text styling options"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'FlashCardBlock', 'interactive', 'content', NULL);
INSERT INTO public.components VALUES (5, '3bd268d4-d5b5-4550-91c6-1865dab19c6a', 'Carousel', 'An interactive image carousel with navigation controls and captions', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "images": {"type": "array", "items": {"type": "object", "properties": {"alt": {"type": "string"}, "src": {"type": "string"}, "caption": {"type": "string"}}}, "required": true, "description": "Array of images with src, alt, and optional caption"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'CarouselBlock', 'interactive', 'content', NULL);
INSERT INTO public.components VALUES (2, 'd7654910-3e03-415f-98b4-71e0ce6a2f0c', 'Table', 'A responsive table component with header row support and mobile card view', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "rows": {"type": "number", "required": true, "description": "Number of rows to display"}, "columns": {"type": "number", "required": true, "description": "Number of columns to display"}, "content": {"type": "array", "items": {"type": "array", "items": {"type": "string"}}, "required": true, "description": "2D array of cell content"}, "headerRow": {"type": "boolean", "default": true, "description": "Whether to display the first row as header"}, "textStyle": {"type": "object", "description": "Text styling options (fontSize, fontWeight, color, fontStyle, textAlign, lineHeight)"}}', '2025-12-06 11:56:44.995', '2025-12-06 11:56:44.995', 1, 'TableBlock', 'static', 'content', NULL);
INSERT INTO public.components VALUES (4, 'ba0cb552-c4c8-4056-979a-51783f521ebe', 'Gallery', 'A horizontal scrollable image gallery', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "images": {"type": "array", "items": {"type": "object", "properties": {"alt": {"type": "string"}, "src": {"type": "string"}}}, "required": true, "description": "Array of images with src and optional alt text"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'GalleryBlock', 'static', 'content', NULL);
INSERT INTO public.components VALUES (6, '0442ca57-14dd-448d-a7e4-182cc37301fb', 'Timeline', 'A vertical timeline displaying events with dates, titles and descriptions', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "events": {"type": "array", "items": {"type": "object", "properties": {"date": {"type": "string"}, "title": {"type": "string"}, "description": {"type": "string"}}}, "required": true, "description": "Array of timeline events"}, "textStyle": {"type": "object", "description": "Text styling options"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options (backgroundColor, padding, borderRadius)"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'TimelineBlock', 'static', 'content', NULL);
INSERT INTO public.components VALUES (9, '6c70c10f-327a-4492-8dc8-a6ae795bdaf5', 'Testimonial', 'Display testimonials in a grid layout with avatars and roles', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "textStyle": {"type": "object", "description": "Text styling options"}, "testimonials": {"type": "array", "items": {"type": "object", "properties": {"name": {"type": "string"}, "role": {"type": "string"}, "title": {"type": "string"}, "avatar": {"type": "string"}, "content": {"type": "string"}}}, "required": true, "description": "Array of testimonials"}, "backgroundImage": {"type": "string", "description": "Optional background image URL"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'TestimonialBlock', 'static', 'content', NULL);
INSERT INTO public.components VALUES (56, '5c02f66b-b51b-4e22-bfbf-acdea506e39f', 'Video', 'Embed videos from YouTube, Vimeo or direct URLs', '{"url": {"type": "string", "required": true, "description": "Video URL (YouTube, Vimeo, or direct)"}, "dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "title": {"type": "string", "default": "Video", "description": "Video title for accessibility"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'VideoBlock', 'interactive', 'content', NULL);
INSERT INTO public.components VALUES (22, '11c40dc2-e9e9-40cd-9bf4-0ff4377ed227', 'Multiple Choice', 'A single-answer multiple choice question with feedback', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "text": {"type": "string"}, "feedback": {"type": "string"}, "isCorrect": {"type": "boolean"}}}, "required": true, "description": "Array of answer options"}, "question": {"type": "string", "description": "The question text"}, "textStyle": {"type": "object", "description": "Text styling options"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'MultipleChoiceBlock', 'interactive', 'exercise', NULL);
INSERT INTO public.components VALUES (58, '24b44974-d9b7-44ca-9e85-8f1d77f65b31', 'Attachment', 'Display downloadable file attachments with type-specific icons', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "textStyle": {"type": "object", "description": "Text styling options"}, "attachments": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "url": {"type": "string"}, "name": {"type": "string"}, "size": {"type": "string"}, "type": {"type": "string"}}}, "required": true, "description": "Array of file attachments"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'AttachmentBlock', 'interactive', 'content', NULL);
INSERT INTO public.components VALUES (27, '9b7612b6-1370-420d-bd81-ee3f72987ebe', 'Paragraph with Subheading', 'A paragraph block with a subheading above it', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "content": {"type": "string", "required": true, "description": "The paragraph text content"}, "subheading": {"type": "string", "required": true, "description": "The subheading text"}, "contentStyle": {"type": "object", "description": "Content text styling options"}, "subheadingStyle": {"type": "object", "description": "Subheading styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ParagraphWithSubheadingBlock', 'static', 'content', 'paragraph');
INSERT INTO public.components VALUES (25, 'b0f327ea-b7fb-4da9-90a4-b3da71992dd4', 'Paragraph', 'A simple text paragraph block', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "content": {"type": "string", "required": true, "description": "The paragraph text content"}, "contentStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ParagraphBlock', 'static', 'content', 'paragraph');
INSERT INTO public.components VALUES (26, '3e07fb02-a003-40b7-9f68-356c005fdea2', 'Paragraph with Heading', 'A paragraph block with a heading above it', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "content": {"type": "string", "required": true, "description": "The paragraph text content"}, "heading": {"type": "string", "required": true, "description": "The heading text"}, "contentStyle": {"type": "object", "description": "Content text styling options"}, "headingStyle": {"type": "object", "description": "Heading styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ParagraphWithHeadingBlock', 'static', 'content', 'paragraph');
INSERT INTO public.components VALUES (29, 'f7201991-f5dc-4b9f-8a4b-8feafcea2b8b', 'Heading', 'A heading element with configurable level (h1-h6)', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "level": {"enum": [1, 2, 3, 4, 5, 6], "type": "number", "default": 1, "description": "Heading level (1-6)"}, "heading": {"type": "string", "required": true, "description": "The heading text"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'HeadingBlock', 'static', 'content', 'heading');
INSERT INTO public.components VALUES (30, '9da6e9ab-7524-4c0d-a4eb-3c03dbe1b9f0', 'Subheading', 'A subheading element (renders as h3)', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "textStyle": {"type": "object", "description": "Text styling options"}, "subheading": {"type": "string", "required": true, "description": "The subheading text"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'SubheadingBlock', 'static', 'content', 'heading');
INSERT INTO public.components VALUES (31, 'a290febc-4ee8-4606-873e-b97afac04ba4', 'Highlight Note', 'A highlighted note with colored left border and background', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "highlight": {"type": "string", "required": true, "description": "The highlighted text"}, "textStyle": {"type": "object", "description": "Text styling options"}, "blockStyle": {"enum": ["A", "B", "C"], "type": "string", "default": "A", "description": "Color theme variant (A=yellow, B=blue, C=purple)"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'HighlightNoteBlock', 'static', 'content', 'highlight');
INSERT INTO public.components VALUES (32, 'a94adc7f-ec5d-40ad-bad9-997471765a54', 'Highlight', 'A highlighted text block (alias for HighlightNoteBlock)', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "highlight": {"type": "string", "required": true, "description": "The highlighted text"}, "textStyle": {"type": "object", "description": "Text styling options"}, "blockStyle": {"enum": ["A", "B", "C"], "type": "string", "default": "A", "description": "Color theme variant"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'HighlightBlock', 'static', 'content', 'highlight');
INSERT INTO public.components VALUES (33, '6b11b023-6242-4b15-8a4b-68d77716c3bf', 'Highlight Column', 'A centered highlighted text in a narrow column', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "highlight": {"type": "string", "required": true, "description": "The highlighted text"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'HighlightColumnBlock', 'static', 'content', 'highlight');
INSERT INTO public.components VALUES (34, 'cba8707b-a025-43db-a2f3-eff563f660ed', 'Highlight Center Line', 'A centered highlighted text with a decorative line above', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "highlight": {"type": "string", "required": true, "description": "The highlighted text"}, "lineColor": {"type": "string", "default": "#9F80DA", "description": "Color of the decorative line"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'HighlightCenterLineBlock', 'static', 'content', 'highlight');
INSERT INTO public.components VALUES (35, 'c4321ad6-ae71-4f97-9bf0-73e82cde9886', 'Highlight Left Line', 'A left-aligned highlighted text with a decorative line above', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "highlight": {"type": "string", "required": true, "description": "The highlighted text"}, "lineColor": {"type": "string", "default": "#9F80DA", "description": "Color of the decorative line"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'HighlightLeftLineBlock', 'static', 'content', 'highlight');
INSERT INTO public.components VALUES (36, '75bf8bf7-a5f8-4efc-9f72-baca2f696d8e', 'Highlight Background', 'A highlighted text with a solid background', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "highlight": {"type": "string", "required": true, "description": "The highlighted text"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'HighlightBackgroundBlock', 'static', 'content', 'highlight');
INSERT INTO public.components VALUES (37, '0a4417f2-f784-4824-8d65-998817a54329', 'Image', 'A simple image block', '{"alt": {"type": "string", "default": "Image", "description": "Alt text for the image"}, "dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "image": {"type": "string", "required": true, "description": "Image URL"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ImageBlock', 'static', 'content', 'image');
INSERT INTO public.components VALUES (38, '3a8cce18-2053-405b-ae69-20d130aaa194', 'Image with Text Right', 'An image with text displayed to the right side', '{"alt": {"type": "string", "default": "Image", "description": "Alt text for the image"}, "dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "text": {"type": "string", "required": true, "description": "Text content"}, "image": {"type": "string", "required": true, "description": "Image URL"}, "textStyle": {"type": "object", "description": "Text styling options"}, "textBackgroundStyle": {"type": "object", "description": "Text area background styling"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ImageWithTextBlock', 'static', 'content', 'image');
INSERT INTO public.components VALUES (39, '46f8f6ee-2491-40dd-9f8c-98375638c014', 'Image with Text Left', 'An image with text displayed to the left side', '{"alt": {"type": "string", "default": "Image", "description": "Alt text for the image"}, "dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "text": {"type": "string", "required": true, "description": "Text content"}, "image": {"type": "string", "required": true, "description": "Image URL"}, "textStyle": {"type": "object", "description": "Text styling options"}, "textBackgroundStyle": {"type": "object", "description": "Text area background styling"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ImageWithTextLeftBlock', 'static', 'content', 'image');
INSERT INTO public.components VALUES (40, '425c5eef-3cb5-4653-b181-ed7481aba77f', 'Image with Text Center', 'An image with text overlaid in the center', '{"alt": {"type": "string", "default": "Image", "description": "Alt text for the image"}, "dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "text": {"type": "string", "required": true, "description": "Text content"}, "image": {"type": "string", "required": true, "description": "Image URL"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ImageWithTextCenterBlock', 'static', 'content', 'image');
INSERT INTO public.components VALUES (41, '5b46f001-f4d5-455f-8e75-0c2e76ad4c32', 'Image with Text Bottom', 'An image with text displayed below', '{"alt": {"type": "string", "default": "Image", "description": "Alt text for the image"}, "dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "text": {"type": "string", "required": true, "description": "Text content"}, "image": {"type": "string", "required": true, "description": "Image URL"}, "textStyle": {"type": "object", "description": "Text styling options"}, "textBackgroundStyle": {"type": "object", "description": "Text area background styling"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ImageWithTextBottomBlock', 'static', 'content', 'image');
INSERT INTO public.components VALUES (42, '3bdbec9d-58e4-4281-9e91-bedf227569fb', 'Image with Text Top', 'An image with text displayed above', '{"alt": {"type": "string", "default": "Image", "description": "Alt text for the image"}, "dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "text": {"type": "string", "required": true, "description": "Text content"}, "image": {"type": "string", "required": true, "description": "Image URL"}, "textStyle": {"type": "object", "description": "Text styling options"}, "textBackgroundStyle": {"type": "object", "description": "Text area background styling"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ImageWithTextTopBlock', 'static', 'content', 'image');
INSERT INTO public.components VALUES (14, 'c6156205-3d36-4f9a-b6f5-aa8252606a15', 'Quote Center Border', 'A centered quote with customizable border styling', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "author": {"type": "string", "description": "Author name"}, "avatar": {"type": "string", "description": "Author avatar image URL"}, "content": {"type": "string", "required": true, "description": "The quote text"}, "textStyle": {"type": "object", "description": "Text styling options"}, "borderColor": {"type": "string", "default": "#E5E7EB", "description": "Border color"}, "borderWidth": {"type": "number", "default": 1, "description": "Border width in pixels"}, "borderRadius": {"type": "number", "default": 16, "description": "Border radius in pixels"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'QuoteCenterBorderBlock', 'static', 'content', 'quote');
INSERT INTO public.components VALUES (15, '0f74e4d8-52d4-41a7-97c3-ab01995fbee2', 'Quote Center Light', 'A minimal centered quote with light styling', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "author": {"type": "string", "description": "Author name"}, "avatar": {"type": "string", "description": "Author avatar image URL"}, "content": {"type": "string", "required": true, "description": "The quote text"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'QuoteCenterLightBlock', 'static', 'content', 'quote');
INSERT INTO public.components VALUES (16, 'fe58e023-927a-4bfd-ae99-249907cfe72e', 'Quote Left Light', 'A left-aligned quote with light styling and optional avatar', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "author": {"type": "string", "description": "Author name"}, "avatar": {"type": "string", "description": "Author avatar image URL"}, "content": {"type": "string", "required": true, "description": "The quote text"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'QuoteLeftLightBlock', 'static', 'content', 'quote');
INSERT INTO public.components VALUES (17, 'ec9195ea-4522-40d0-b22c-7904e6d809e9', 'Quote Left', 'A left-aligned quote with background styling', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "author": {"type": "string", "description": "Author name"}, "avatar": {"type": "string", "description": "Author avatar image URL"}, "content": {"type": "string", "required": true, "description": "The quote text"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'QuoteLeftBlock', 'static', 'content', 'quote');
INSERT INTO public.components VALUES (13, '1162f8b9-a723-47e1-b334-d5a9372d76b3', 'Quote', 'Display a quote with optional author, avatar, title and background image', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "title": {"type": "string", "description": "Quote title"}, "author": {"type": "string", "description": "Author name"}, "avatar": {"type": "string", "description": "Author avatar image URL"}, "content": {"type": "string", "required": true, "description": "The quote text"}, "textStyle": {"type": "object", "description": "Text styling options"}, "backgroundImage": {"type": "string", "description": "Background image URL"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'QuoteBlock', 'static', 'content', 'quote');
INSERT INTO public.components VALUES (18, 'f8b322ee-07c0-4292-9f1f-d7e923a56ef2', 'Quote Image', 'A quote displayed over a background image with overlay', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "author": {"type": "string", "description": "Author name"}, "avatar": {"type": "string", "description": "Author avatar image URL"}, "content": {"type": "string", "required": true, "description": "The quote text"}, "textStyle": {"type": "object", "description": "Text styling options"}, "overlayOpacity": {"type": "number", "default": 0.5, "description": "Opacity of the dark overlay (0-1)"}, "backgroundImage": {"type": "string", "required": true, "description": "Background image URL"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'QuoteImageBlock', 'static', 'content', 'quote');
INSERT INTO public.components VALUES (43, '558d0179-2f65-44e4-b6c7-b77f7ca80105', 'Pros and Cons', 'A side-by-side comparison of pros and cons', '{"cons": {"type": "array", "items": {"type": "string"}, "required": true, "description": "Array of cons/disadvantages"}, "dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "pros": {"type": "array", "items": {"type": "string"}, "required": true, "description": "Array of pros/advantages"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ComparisonProsConsBlock', 'static', 'content', 'comparison');
INSERT INTO public.components VALUES (44, '737440a0-858a-4840-a358-e63b3923135b', 'Cause and Effect', 'Display cause and effect relationship with arrow connector', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "cause": {"type": "string", "required": true, "description": "The cause text"}, "effect": {"type": "string", "required": true, "description": "The effect text"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ComparisonCauseEffectBlock', 'static', 'content', 'comparison');
INSERT INTO public.components VALUES (45, 'd3dc4738-b149-403c-a7de-426b8df4aed3', 'Dos and Donts', 'A side-by-side comparison of dos and donts', '{"dos": {"type": "array", "items": {"type": "string"}, "required": true, "description": "Array of recommended actions"}, "dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "donts": {"type": "array", "items": {"type": "string"}, "required": true, "description": "Array of actions to avoid"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ComparisonDosDontsBlock', 'static', 'content', 'comparison');
INSERT INTO public.components VALUES (46, 'e9148f95-ea2b-4b6f-9835-151dd191b3b4', 'Myth vs Fact', 'Display a myth and its corresponding fact', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "fact": {"type": "string", "required": true, "description": "The fact text"}, "myth": {"type": "string", "required": true, "description": "The myth text"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ComparisonMythFactBlock', 'static', 'content', 'comparison');
INSERT INTO public.components VALUES (47, 'd329e811-663b-412f-8bef-7b71a85c8907', 'Comparison', 'A flexible comparison grid with multiple items and style variants', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "object", "properties": {"title": {"type": "string"}, "content": {"type": "string"}}}, "required": true, "description": "Array of comparison items"}, "textStyle": {"type": "object", "description": "Text styling options"}, "blockStyle": {"enum": ["A", "B", "C"], "type": "string", "default": "A", "description": "Visual style variant"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ComparisonBlock', 'static', 'content', 'comparison');
INSERT INTO public.components VALUES (48, '6fa98b55-875c-43a7-afad-9854e37d08ca', 'Before and After', 'A side-by-side comparison of before and after states', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "textStyle": {"type": "object", "description": "Text styling options"}, "afterItems": {"type": "array", "items": {"type": "string"}, "required": true, "description": "Array of after items"}, "beforeItems": {"type": "array", "items": {"type": "string"}, "required": true, "description": "Array of before items"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ComparisonBeforeAfterBlock', 'static', 'content', 'comparison');
INSERT INTO public.components VALUES (49, '989b8388-5679-4b30-bd0f-8bcb70caab5d', 'Chat Feedback', 'A chat conversation display with avatars, names and timestamps', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "sender": {"type": "object", "required": true, "properties": {"name": {"type": "string"}, "avatar": {"type": "string"}}, "description": "Sender participant info"}, "messages": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "time": {"type": "string"}, "content": {"type": "string"}, "isSender": {"type": "boolean"}}}, "required": true, "description": "Array of chat messages"}, "receiver": {"type": "object", "required": true, "properties": {"name": {"type": "string"}, "avatar": {"type": "string"}}, "description": "Receiver participant info"}, "textStyle": {"type": "object", "description": "Text styling options"}, "senderBubbleColor": {"type": "string", "default": "#9F80DA", "description": "Sender message bubble color"}, "receiverBubbleColor": {"type": "string", "description": "Receiver message bubble color"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ChatFeedbackBlock', 'static', 'content', 'chat');
INSERT INTO public.components VALUES (50, '2451a00e-ece6-44c2-af27-d055da88add0', 'Chat Q&A', 'A Q&A style chat without avatars and timestamps', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "sender": {"type": "object", "required": true, "properties": {"name": {"type": "string"}}, "description": "Sender participant info"}, "messages": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "content": {"type": "string"}, "isSender": {"type": "boolean"}}}, "required": true, "description": "Array of chat messages"}, "receiver": {"type": "object", "required": true, "properties": {"name": {"type": "string"}}, "description": "Receiver participant info"}, "textStyle": {"type": "object", "description": "Text styling options"}, "senderBubbleColor": {"type": "string", "default": "#9F80DA", "description": "Sender message bubble color"}, "receiverBubbleColor": {"type": "string", "description": "Receiver message bubble color"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ChatQABlock', 'static', 'content', 'chat');
INSERT INTO public.components VALUES (51, '3b6cb293-8273-45bf-9b6a-92b26d3fb40e', 'Question Wall', 'A two-column display of questions and their answers', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "object", "properties": {"answer": {"type": "string"}, "question": {"type": "string"}}}, "required": true, "description": "Array of question-answer pairs"}, "textStyle": {"type": "object", "description": "Text styling options"}, "answerBubbleColor": {"type": "string", "default": "#9F80DA", "description": "Answer bubble color"}, "questionBubbleColor": {"type": "string", "default": "#E5E7EB", "description": "Question bubble color"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ChatQuestionWallBlock', 'static', 'content', 'chat');
INSERT INTO public.components VALUES (52, 'd4ec5ffe-18d7-4e85-86a0-b8200bdd8f9c', 'Chat Dialog', 'A simple alternating dialog conversation', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "messages": {"type": "array", "items": {"type": "object", "properties": {"text": {"type": "string"}, "isLeft": {"type": "boolean"}}}, "required": true, "description": "Array of dialog messages"}, "textStyle": {"type": "object", "description": "Text styling options"}, "leftBubbleColor": {"type": "string", "default": "#E5E7EB", "description": "Left side bubble color"}, "rightBubbleColor": {"type": "string", "default": "#9F80DA", "description": "Right side bubble color"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ChatDialogBlock', 'static', 'content', 'chat');
INSERT INTO public.components VALUES (53, 'd51021c8-cf78-458b-988d-1519b034d443', 'Chat', 'A full-featured chat conversation (alias for ChatFeedbackBlock)', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "sender": {"type": "object", "required": true, "properties": {"name": {"type": "string"}, "avatar": {"type": "string"}}, "description": "Sender participant info"}, "messages": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "time": {"type": "string"}, "content": {"type": "string"}, "isSender": {"type": "boolean"}}}, "required": true, "description": "Array of chat messages"}, "receiver": {"type": "object", "required": true, "properties": {"name": {"type": "string"}, "avatar": {"type": "string"}}, "description": "Receiver participant info"}, "textStyle": {"type": "object", "description": "Text styling options"}, "senderBubbleColor": {"type": "string", "default": "#9F80DA", "description": "Sender message bubble color"}, "receiverBubbleColor": {"type": "string", "description": "Receiver message bubble color"}, "textBackgroundStyle": {"type": "object", "description": "Background styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ChatBlock', 'static', 'content', 'chat');
INSERT INTO public.components VALUES (21, 'ba332d39-91a1-444b-ae3f-f215b2f24ead', 'Sorting Steps', 'An interactive drag-and-drop sorting exercise to arrange items in correct order', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "title": {"type": "string"}, "content": {"type": "string"}, "correctOrder": {"type": "number"}}}, "required": true, "description": "Array of items to be sorted"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'SortingStepsBlock', 'interactive', 'exercise', 'sorting');
INSERT INTO public.components VALUES (62, '984f43cb-c8c7-4663-9336-68af74261be3', 'Sorting', 'An interactive card sorting exercise into categories', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "cards": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "title": {"type": "string"}, "content": {"type": "string"}, "correctCategory": {"type": "string"}}}, "required": true, "description": "Array of cards to sort"}, "categories": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "title": {"type": "string"}}}, "required": true, "description": "Array of category destinations"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'SortingBlock', 'interactive', 'exercise', 'sorting');
INSERT INTO public.components VALUES (12, '5a27d2de-79bb-4eb4-894c-699a1b377eb2', 'Button', 'A configurable button or link with icons and multiple style variants', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "rel": {"type": "string"}, "url": {"type": "string"}, "icon": {"type": "string"}, "size": {"enum": ["small", "medium", "large"], "type": "string"}, "text": {"type": "string"}, "label": {"type": "string"}, "style": {"enum": ["primary", "secondary", "tertiary"], "type": "string"}, "layout": {"enum": ["button-left", "button-right", "button-center"], "type": "string"}, "target": {"enum": ["_blank", "_self"], "type": "string"}, "iconSize": {"enum": ["small", "medium", "large"], "type": "string"}, "iconPosition": {"enum": ["left", "right"], "type": "string"}}}, "required": true, "description": "Array of button items"}, "textStyle": {"type": "object", "description": "Text styling options"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ButtonBlock', 'interactive', 'navigation', 'button');
INSERT INTO public.components VALUES (60, '6b322724-5881-41c2-a565-2138dbc9b46e', 'Button Stack', 'A vertical stack of link buttons with multiple style variants', '{"dark": {"type": "boolean", "default": false, "description": "Enable dark mode styling"}, "items": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "url": {"type": "string"}, "icon": {"type": "string"}, "text": {"type": "string"}, "target": {"enum": ["_blank", "_self"], "type": "string"}, "description": {"type": "string"}}}, "required": true, "description": "Array of button items"}, "title": {"type": "string", "description": "Optional title above the stack"}, "textStyle": {"type": "object", "description": "Text styling options"}, "stackStyle": {"enum": ["cards", "minimal", "bordered", "gradient"], "type": "string", "default": "cards", "description": "Visual style of the stack"}, "accentColor": {"type": "string", "default": "#9F80DA", "description": "Accent color for decorations"}}', '2025-12-06 11:56:49.913', '2025-12-06 11:56:49.913', 1, 'ButtonStackBlock', 'interactive', 'navigation', 'button');


--
-- Name: components_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.components_id_seq', 1, false);


--
-- PostgreSQL database dump complete
--

\unrestrict 3pVwQvf9GFfHQCnJzpo6P4Y7zW0oJrHK8ZEXxdz6XZgUT2hlrpdsA8G0hOg3ebV

