apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acadion

namePrefix: ""

resources:
  - ../../base
  - patches/namespace.yaml

patches:
  - path: patches/backend.yaml
  - path: patches/frontend.yaml
  - path: patches/ingress.yaml

configMapGenerator:
  - name: acadion-config
    behavior: create
    literals:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8001
      - FRONTEND_URL=http://dev.acadion.local
      - GOOGLE_CALLBACK_URL=http://dev.acadion.local/api/v1/auth/google/callback
      - JWT_EXPIRES_IN=7d
