version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cursos_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cursos
    ports:
      - "5588:5432"
    volumes:
      - cursos_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cursos_redis
    ports:
      - "6379:6379"
    volumes:
      - cursos_redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  cursos_postgres_data:
  cursos_redis_data:
